language: node_js
node_js:
- '10'
branches:
  only:
    - master
install:
- npm install
before_script:
- npm test
script:
# Render PUG files to HTML files for static pages
- npm run render-static
# Build client application bundles
- npm run build-home-base -- --env.mode=production --env.watch=false
- npm run build-home-auth -- --env.mode=production --env.watch=false
- npm run build-plantId-base -- --env.mode=production --env.watch=false
- npm run build-plantId-auth -- --env.mode=production --env.watch=false
# Render SCSS global file to CSS
- npm run build-styles-global
# Creates the mongo client secret file using ENV variables
- echo -e "{\"username\":\"$MONGO_CLIENT_USERNAME\",\"password\":\"$MONGO_CLIENT_PASSWORD\"}" > ./server/mongo/clientSecret.json
deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: perma-data-5
  on:
    branch: master
  skip_cleanup: true
cache:
  directories:
  - node_modules
env:
  global:
  - secure: nz4XHJgmxJT/CHI07k4PrzKNvFDXNkWedMUfK0CRgvgTJexoujmJ+700w/QZt6grymS4atci22T9XsB5XtOJQqagF0yyoSkcoG90RHGPrahBvIa8CfmXlN64FkrZKC0KS4V4Xcu5TbcjMJnNQpAEBxWxacytm4eW3c/mb8yBOtBkmnWeoCOvRPk8pc63pfNuxDz9Bm+pTD1H+uGYjxF6a38H6AxQccGsk57vwvrkEJH327W3h3t76eOZxzue9SQSUNIUkeHahN5EhMg7vWkLxke7EdRR8Hv5B41VQhJZtV3ZQgoFNM1Yf4+oa+XI9BdFn8VmE+ZesWIIrMVro3ogNtXHNyTv7MZBR/nE/A+oAbIiBcBF4oAi5IJeOdA8ZFUGd7FsGcy/qhJNx72/FBJT09G1t7HrcN22179R+eI/ay/gGKbNNAewSNYBqkXT2N4F9OkHhOrI4Bd78SG+F7iJAb+MwvpBm0mDFaZa6tULB9Bs/aBT3Z9KrRy5d15LgjSGCnpLl0jx8v50ZjoWi6C1/iyRXvFe5WLc7Q7a3tI8xcwiaZvUjpWgSxOGns9qs0f0dWExdCFSmRG3TlooV6pXOwPaPlAUQotdaoYuDQA9bLxgaqGWOOsd1W1wlHTJiWR7H3lamdyAyAbRXDaVQOSQiRE5w8cDJp/vMcJs9pSC9Ho=
  - secure: jY4ScIOOE6eEkAZUsuQZ9pakxgZBm9AC7Qwsh7c+2ktu2SUpqBLmz0pYlpgKI4HPj2CS5A+Kwwrv3OD9GNRbDez8wOpHFT86SWuupY2NFqHdx8IARg6zlZER3eKL/6Yjgc0MCo/NITbM934MlUJ9q0cEgen0SZ0ILgif+KDtQiEt2ZIGW3h5FQIS5+ZWYDaunVwWuTj0JyKYkArFZfXWIaRtNcVk5FyawWdhjdWmlKKg289f1eqU4x3oQXUzMWvbGDQ93wxbYhFXZ6KNHxatKPDG7bUsJvdkZLugrJTJCIrhw/OABovqCmNM0MlPisS6EZM6i1k3v4x1iRvMKpnv+e7siPD/xRNKMg/uYJvUmhlpvX0Tjs8qmPOj8z2ASDEhtcCB7qOMBH0r/ee1VfgyRdJLh5ql4LRXZfBaxXvipTuK2WqPNBdAwpwvT8Ij2wb+S0/KJsRMEGIoVJ4Y6yIMK7bj16qfXzDGMd21CQMZQN51qdVEv7EHpzah11AQGuYEqiFNEO184Zfg5biSj87tEbH9Htxv6W5WZ4ZhPbcJHEqKuo3m9JqufNVzThi3uIE/EwHRmjWLRHjv/1HVQB511p3pDmfUXzG4JSdvdfkHx5+msEiN6ggelUQ91YhSKsxpCPea2ja6hRnqCAWa57Pi3sdsLr2Q4CDCocDYmPLOGYs=
